const assert=require('node:assert/strict');const P=require('../app/src/main/assets/reader109/protocol.js');let checks=0;
for(const n of [1,2,3,4,5,6,7,8,10,11,12,15,16,31]){
 const lines=Array.from({length:n},(_,i)=>'12:'+i);const s=P.create(lines,false),steps=P.plan(lines,false);assert(steps.every(p=>p.lines.every(l=>lines.includes(l))));
 const sizes=P.balancedBlocks(lines).map(b=>b.length);assert.deepEqual(P.balancedBlocks(lines).flat(),lines);if(n<=7)assert.deepEqual(sizes,[n]);else{assert(sizes.every(size=>size<=6&&size>=3));assert(Math.max(...sizes)-Math.min(...sizes)<=1)}
 const expected={4:[4],5:[5],6:[6],7:[7],8:[4,4],10:[5,5],11:[6,5],15:[5,5,5]};if(expected[n])assert.deepEqual(sizes,expected[n]);
 assert.equal(steps[0].label,'Préparation · Lecture attentive');assert.equal(steps[0].min,2);assert.equal(steps[0].kind,'read');
 for(const label of ['Valider — Visible','Valider — 25 %','Valider — 50 %','Valider — 75 %','Valider — 100 %'])assert(steps.some(p=>p.label.startsWith(label)));
 assert.equal(steps.at(-1).label,'Valider le bloc mémorisé');
 while(P.current(s)){const p=P.current(s);assert(!P.validate(s)||p.min===0);if(p.kind==='confirm')continue;for(let i=0;i<Math.max(p.min,3);i++)P.record(s,true);assert(P.canValidate(s));const before=[...s.milestones];P.aid(s,'first-word',1);assert(!P.record(s,true));assert(!P.canValidate(s));assert.deepEqual(s.milestones,before);P.clearAid(s);if(p.success)for(let i=0;i<3;i++)P.record(s,true);assert(P.validate(s));Object.assign(s,JSON.parse(JSON.stringify(s)));checks++;}assert(s.complete);assert.equal(s.status,'Acquis');assert.equal(s.milestones.length,steps.length);
}
const s=P.create(['1:0'],true);assert.equal(P.current(s).kind,'read');P.record(s);assert(!P.canValidate(s));P.record(s);assert(P.canValidate(s));P.validate(s);assert.equal(P.current(s).kind,'passive');assert(!P.record(s));assert(P.record(s,true,'audio'));assert(!P.canValidate(s));P.record(s,true,'audio');assert(P.canValidate(s));P.validate(s);assert.equal(P.current(s).kind,'passive');
const failed=P.create(['1:0'],false);for(let i=0;i<2;i++)P.record(failed);P.record(failed,false);assert.equal(failed.wins[P.current(failed).id],0);assert.equal(failed.counts[P.current(failed).id],3);
const stable=P.create(['1:0'],false);assert.equal(P.rank(stable.seed,'1:0:3'),P.rank(stable.seed,'1:0:3'));const persisted=JSON.parse(JSON.stringify(stable));assert.equal(persisted.seed,stable.seed);
const assisted=P.create(['1:0'],false);while(P.current(assisted).mask!==100){const p=P.current(assisted);for(let i=0;i<p.min;i++)P.record(assisted,true);assert(P.validate(assisted))}const assistedStep=P.current(assisted);assisted.counts[assistedStep.id]=7;assisted.wins[assistedStep.id]=2;P.aid(assisted,'first-word',1);assert.equal(assisted.wins[assistedStep.id],0);assert(!P.record(assisted,true));assert(!P.canValidate(assisted));P.clearAid(assisted);assert(P.record(assisted,true));assert.equal(assisted.wins[assistedStep.id],1);assert(!P.canValidate(assisted));P.aid(assisted,'brief',0);assert(!P.record(assisted,true));P.redo(assisted);assert.equal(assisted.assistance,undefined);assert.equal(assisted.counts[assistedStep.id],0);assert.equal(assisted.wins[assistedStep.id],0);
// If local audio disappears after a session has started, the pedagogical path
// must continue on the non-audio plan without inventing audio completions.
const downgrade=P.create(['1:0','1:1'],true);for(let i=0;i<2;i++)P.record(downgrade,true);assert(P.canValidate(downgrade));assert(P.validate(downgrade));assert.equal(P.current(downgrade).kind,'passive');const savedMilestones=[...downgrade.milestones];assert(P.disableAudio(downgrade));assert.equal(downgrade.withAudio,false);assert.deepEqual(downgrade.milestones,savedMilestones);assert.notEqual(P.current(downgrade)?.kind,'passive');assert.equal(P.disableAudio(downgrade),false);
// Product metric: actual readings stay split into visible versus masked; audio never
// increments either counter and old sessions without readCounts are derived exactly once.
const counted=P.create(['1:0'],true);assert.deepEqual(P.readingCounts(counted),{visible:0,masked:0});P.record(counted,true);assert.deepEqual(P.readingCounts(counted),{visible:1,masked:0});P.record(counted,true);P.validate(counted);assert(P.record(counted,true,'audio'));assert.deepEqual(P.readingCounts(counted),{visible:2,masked:0});
const legacy=P.create(['1:0'],false);delete legacy.readCounts;legacy.counts[P.current(legacy).id]=4;assert.deepEqual(P.readingCounts(legacy),{visible:4,masked:0});P.record(legacy,true);assert.deepEqual(P.readingCounts(legacy),{visible:5,masked:0});
const masked=P.create(['1:0'],false);while(P.current(masked).mask===0){const p=P.current(masked);for(let i=0;i<p.min;i++)P.record(masked,true);P.validate(masked)}P.record(masked,true);assert(P.readingCounts(masked).masked>0);const beforeReinforcement=P.readingCounts(masked).masked;P.recordMaskedReading(masked);assert.equal(P.readingCounts(masked).masked,beforeReinforcement+1);
for(let i=0;i<100;i++){const rank=P.rank(42,'line:'+i);assert.equal(rank,P.rank(42,'line:'+i));assert(rank>=0&&rank<1)}
console.log('PASS',checks,'milestone transitions; short, normal, long, preparation, restart, aid, audio isolation, local-audio downgrade and split reading counters');