const assert=require('node:assert/strict');const P=require('../app/src/main/assets/reader109/protocol.js');let checks=0;
for(const n of [1,2,3,4,5,6,7,8,10,11,12,15,16,31]){
 const lines=Array.from({length:n},(_,i)=>'12:'+i);const s=P.create(lines,false),steps=P.plan(lines,false);assert(steps.every(p=>p.lines.every(l=>lines.includes(l))));
 const sizes=P.balancedBlocks(lines).map(b=>b.length);assert.deepEqual(P.balancedBlocks(lines).flat(),lines);if(n<=7)assert.deepEqual(sizes,[n]);else{assert(sizes.every(size=>size<=6&&size>=3));assert(Math.max(...sizes)-Math.min(...sizes)<=1)}
 const expected={4:[4],5:[5],6:[6],7:[7],8:[4,4],10:[5,5],11:[6,5],15:[5,5,5]};if(expected[n])assert.deepEqual(sizes,expected[n]);
 assert.equal(steps[0].label,'Préparation · Lecture attentive');assert.equal(steps[0].min,2);assert.equal(steps[0].kind,'read');
 for(const label of ['Valider — Visible','Valider — 25 %','Valider — 50 %','Valider — 75 %','Valider — 100 %'])assert(steps.some(p=>p.label.startsWith(label)));
 assert.equal(steps.at(-1).label,'Valider le bloc mémorisé');
 while(P.current(s)){const p=P.current(s);assert(!P.validate(s)||p.min===0);if(p.kind==='confirm')continue;for(let i=0;i<Math.max(p.min,3);i++)P.record(s,true);assert(P.canValidate(s));const before=[...s.milestones];P.aid(s,'first-word',1);assert(!P.record(s,true));assert(!P.canValidate(s));assert.deepEqual(s.milestones,before);P.clearAid(s);if(p.success)for(let i=0;i<3;i++)P.record(s,true);assert(P.validate(s));Object.assign(s,JSON.parse(JSON.stringify(s)));checks++;}assert(s.complete);assert.equal(s.status,'Acquis');assert.equal(s.milestones.length,steps.length);
}
const s=P.create(['1:0'],true);assert.equal(P.current(s).kind,'read');P.record(s);assert(!P.canValidate(s));P.record(s);assert(P.canValidate(s));P.validate(s);assert.equal(P.current(s).kind,'passive');assert(!P.record(s));assert(P.record(s,true,'audio'));assert(!P.canValidate(s));P.record(s,true,'audio');assert(P.canValidate(s));P.validate(s);assert.equal(P.current(s).kind,'passive');
const failed=P.create(['1:0'],false);for(let i=0;i<2;i++)P.record(failed);P.record(failed,false);assert.equal(failed.wins[P.current(failed).id],0);assert.equal(failed.counts[P.current(failed).id],3);
const stable=P.create(['1:0'],false);assert.equal(P.rank(stable.seed,'1:0:3'),P.rank(stable.seed,'1:0:3'));const persisted=JSON.parse(JSON.stringify(stable));assert.equal(persisted.seed,stable.seed);
const assisted=P.create(['1:0'],false);while(P.current(assisted).mask!==100){const p=P.current(assisted);for(let i=0;i<p.min;i++)P.record(assisted,true);assert(P.validate(assisted))}const assistedStep=P.current(assisted);assisted.counts[assistedStep.id]=7;assisted.wins[assistedStep.id]=2;P.aid(assisted,'first-word',1);assert.equal(assisted.wins[assistedStep.id],0);assert(!P.record(assisted,true));assert(!P.canValidate(assisted));P.clearAid(assisted);assert(P.record(assisted,true));assert.equal(assisted.wins[assistedStep.id],1);assert(!P.canValidate(assisted));P.aid(assisted,'brief',0);assert(!P.record(assisted,true));P.redo(assisted);assert.equal(assisted.assistance,undefined);assert.equal(assisted.counts[assistedStep.id],0);assert.equal(assisted.wins[assistedStep.id],0);
for(let i=0;i<100;i++){const rank=P.rank(42,'line:'+i);assert.equal(rank,P.rank(42,'line:'+i));assert(rank>=0&&rank<1)}
console.log('PASS',checks,'milestone transitions; short, normal, long, preparation, restart, aid, audio isolation');
